# Generated by Django 2.1.15 on 2021-01-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210111_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_post',
        ),
    ]
