# Generated by Django 2.1.15 on 2021-01-12 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210112_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, related_name='writes', to='posts.Author'),
        ),
    ]
